### ISSUE TITLE
500 error in historical API docs file due to Katex

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#673]
https://docs.quantum.ibm.com/api/qiskit/0.42/qiskit.algorithms.linear_solvers.AbsoluteAverage has a 500 error. I suspect due to invalid math as we changed recently some of our code to pre-process math expressions.

--

I think this was not caught by our CI job to check that all pages render because we are using an outdated Docker image in `./start` that doesn't have those math expressions. The page renders fine on `localhost:3000` when using `./start`. So, the first step is to re-release the Docker image used by `./start` and then rerun our Pages Render CI job to see what other pages are also broken.

Update: this was indeed true. It is now fixed.

--

Note that we cannot change the source code for historical Qiskit docs easily because we can't regenerate those docs. So we have a few options:

1. Change the copy of the files from qiskit.org that we've been using. Make sure everyone uses the updated values.
2. Add special-casing code to our API generation script in this repo
3. Add special-casing code to the app itself in the internal repo

This is going to be a problem for fixing historical link 404s, too: https://github.com/Qiskit/documentation/issues/495

I strongly suspect that the best fix is changing iqp-channel-docs. Note that the file used to render fine, so I believe this was an issue with the special casing we added to the docs app to handle MathJax -> Katex. We probably are mis-applying a rule.

**Comment by Eric-Arellano** [comment]
This is still broken even with a recent change made to the docs platform.

```
Error compiling file.
ParseError: KaTeX parse error: Undefined control sequence: \abs at position 1: \̲a̲b̲s̲{\frac{1}{N}\su…
    at new ParseError (/home/node/app/packages/preview/.next/server/chunks/108.js:37:524676)
    at Parser.parseGroup (/home/node/app/packages/preview/.next/server/chunks/108.js:37:802815)
    at Parser.parseAtom (/home/node/app/packages/preview/.next/server/chunks/108.js:37:797200)
    at Parser.parseExpression (/home/node/app/packages/preview/.next/server/chunks/108.js:37:796118)
    at Parser.parse (/home/node/app/packages/preview/.next/server/chunks/108.js:37:795592)
    at parseTree (/home/node/app/packages/preview/.next/server/chunks/108.js:37:805474)
    at renderToDomTree (/home/node/app/packages/preview/.next/server/chunks/108.js:37:806448)
    at Object.renderToString (/home/node/app/packages/preview/.next/server/chunks/108.js:37:806588)
    at /home/node/app/packages/preview/.next/server/app/(docs)/[[...slug]]/page.js:1:32821
    at node (element<span>) (/home/node/app/packages/preview/.next/server/chunks/108.js:42:296222) {
  position: 0,
  length: 4,
  rawMessage: 'Undefined control sequence: \\abs'
}
```

To reproduce, run this locally:

```
docker pull
./start
```

Then go to http://localhost:3000/api/qiskit/0.42/qiskit.algorithms.linear_solvers.AbsoluteAverage.

**Comment by Eric-Arellano** [comment]
Here are all the pages that fail to render:

```
docs/api/qiskit/0.19/qiskit.circuit.library.PauliFeatureMap.md
docs/api/qiskit/0.19/qiskit.quantum_info.OneQubitEulerDecomposer.md
docs/api/qiskit/0.19/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.19/qiskit.quantum_info.purity.md
docs/api/qiskit/0.24/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.24/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.25/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.25/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.25/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.26/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.26/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.26/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.27/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.27/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.27/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.28/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.29/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.30/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.31/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.32/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.33/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.34/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.34/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.35/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.36/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.36/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.37/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.38/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.39/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.40/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.41/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.42/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
```

**Comment by Eric-Arellano** [comment]
These are the pages that fail now.

```
docs/api/qiskit/0.19/qiskit.circuit.library.PauliFeatureMap.md
docs/api/qiskit/0.19/qiskit.quantum_info.OneQubitEulerDecomposer.md
docs/api/qiskit/0.19/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.19/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.19/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.19/qiskit.quantum_info.purity.md
docs/api/qiskit/0.24/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.24/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.24/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.24/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.25/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.25/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.25/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.25/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.25/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.26/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.26/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.26/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.26/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.26/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.27/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.27/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.27/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.27/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.27/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.28/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.28/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.28/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.29/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.29/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.29/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.30/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.30/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.30/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.31/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.31/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.31/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.32/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.32/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.32/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.33/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.33/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.33/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.35/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.35/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.36/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.36/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.37/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.37/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.38/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.38/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.39/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.39/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.40/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.40/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.41/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.41/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.42/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.42/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.43/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.43/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.44/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.44/qiskit.quantum_info.StabilizerTable.md
```

---

Some of them are new failures: 

```
docs/api/qiskit/0.19/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.19/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.24/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.24/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.25/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.25/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.26/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.26/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.27/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.27/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.28/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.28/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.29/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.29/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.30/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.30/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.31/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.31/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.32/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.32/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.33/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.33/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.35/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.35/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.36/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.36/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.37/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.37/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.38/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.38/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.39/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.39/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.40/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.40/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.41/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.41/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.42/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.42/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.43/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.43/qiskit.quantum_info.StabilizerTable.md
docs/api/qiskit/0.44/qiskit.quantum_info.PauliTable.md
docs/api/qiskit/0.44/qiskit.quantum_info.StabilizerTable.md
```

So it's plausible that they fail due to changes made from https://github.com/Qiskit/documentation/pull/718 and https://github.com/Qiskit/documentation/pull/683. It'd be useful to look at the Git history for files that used to be okay and now aren't.

--

These files were fixed presumably thanks to https://github.com/Qiskit/documentation/pull/763:

```
docs/api/qiskit/0.34/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.34/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.36/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.36/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.37/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.38/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.39/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.40/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.41/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.42/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
```

--

These continue to fail before and after:

```
docs/api/qiskit/0.19/qiskit.circuit.library.PauliFeatureMap.md
docs/api/qiskit/0.19/qiskit.quantum_info.OneQubitEulerDecomposer.md
docs/api/qiskit/0.19/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.19/qiskit.quantum_info.purity.md
docs/api/qiskit/0.24/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.24/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.25/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.25/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.25/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.26/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.26/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.26/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.27/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.27/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.27/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.28/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.29/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.30/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.31/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.32/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.33/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.quantum_info.Pauli.md
```

**Comment by Eric-Arellano** [comment]
https://github.com/Qiskit/documentation/pull/767 fixed a lot of issues. After that, here is what fails:

```
docs/api/qiskit/0.19/qiskit.circuit.library.PauliFeatureMap.md
docs/api/qiskit/0.19/qiskit.quantum_info.OneQubitEulerDecomposer.md
docs/api/qiskit/0.19/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.19/qiskit.quantum_info.purity.md
docs/api/qiskit/0.24/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.24/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.25/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.25/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.25/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.26/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.26/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.26/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.27/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.27/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.27/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.28/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.29/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.30/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.31/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.32/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.33/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.quantum_info.Pauli.md
```

There are now no new failures from before. These were all original failures, too.

**Comment by Eric-Arellano** [comment]
All fixed! Thanks @kevinsung.

We should land https://github.com/Qiskit/documentation/issues/773 soon to avoid any regressions.
